language: node_js
node_js:
- node
install:
- yarn install
script:
- yarn build
- yarn test
deploy:
  provider: npm
  email: sreetamdas@gmail.com
  api_key:
    secure: MWi8VGqUHeQ1yS/t5raaZAsjjAL6dcZSZ766PsVtF3OSQjh3b9+cbUMyMfrbXOMqva3pOsT7duTkGMuYOuQv7r2I7oa07Ys+I5jhIeyBe5llnORxFxFvKb3Q4nGQfhuP3EC5d+yladKmmsQgG1/yZXv1GqT3SE2Zs6WQakwl7SSOzgdCWwrPh3SN2T6e3tjkvDkTDgaPsGsNuNc85GFHLIETJErvLUMQC8/hUi2TUGs/Be+SoxXBRGF4GbDnTAlySehKYuXxrzRiLa1NzK0XtO3XJ61YboTaSY1y1odDJ8dHnbbFli6hZCx6aWmzLNOjvj4d6DCe9q9XYVPywSwkoh7zUv4bPw7TaDqtLhTOIrfSamjK4a2uxY5djnam+9vOgCLxsSr9jbwdlY6aWG4yV0tGDPznBZXWwuAsmDD+xXoT1hO+n03u9aK7eEwVjB1DO4E1WOVN9cWsYof1TyRd9DGhd/478vYR4g+BYDR7/lhDbevgSZmkQsqPzybIWVuJSsdL+x+h9rLrHtIhvkIqs+QcZUioB09Z6j5gJ8qDuZDOY/8kW+b23Er5pP223WSoydJYasssnsz20jU0t+USde8jD19w2CdWfJl9CmGrNOs3hi9utwgJdxtfsQ1AlOndr91vSr27uyM5PujNmd/3KC2b0F8kzhEQB4f6wXLpxZo=
  on:
    tags: true
    repo: sreetamdas/react-progress-line
